// AUTO-GENERATED by scripts/sync-icons.mjs — do not edit by hand.
// Maps a target id to its icon filename when it is NOT the default
// `<id>.png` (i.e. an svg/webp/ico override). Lets the app serve vector
// icons directly. Regenerated on every `pnpm dev`/`build`.
export const ICON_OVERRIDES: Record<string, string> = {
  "akamai": "akamai.svg",
  "aliyun": "aliyun.svg",
  "digitalocean": "digitalocean.svg",
  "jd": "jd.svg",
  "ovh": "ovh.svg",
  "twitch": "twitch.svg",
};
