// Copies manual icon overrides from icons-override/ into public/icons/,
// overwriting the auto-fetched versions. Runs automatically before dev/build
// (predev/prebuild), so overrides always win. Offline and fast.
//
// It also emits src/config/icon-overrides.ts, a generated map of target id ->
// icon filename for every override that is NOT the default `<id>.png` (i.e. an
// svg/webp/ico). targets.ts reads it so the app can serve vector (svg) icons
// directly — no rasterization needed. Drop an `<id>.svg` in icons-override/ and
// it just works on the next dev/build.
//
// Finally it PRUNES public/icons/: any icon file that no live target resolves to
// is deleted (keeping public/icons/ in lock-step with targets.ts). The source
// icons-override/ folder is never touched — staged overrides for sites that are
// not (yet) targets simply stay there, unused, until their target is added.
import { mkdir, readdir, copyFile, writeFile, rm, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "icons-override");
const OUT = path.join(ROOT, "public", "icons");
const MANIFEST = path.join(ROOT, "src", "config", "icon-overrides.ts");
const TARGETS = path.join(ROOT, "src", "config", "targets.ts");
const TARGETS_DIR = path.join(ROOT, "src", "config", "targets");

const ICON_RE = /\.(png|svg|ico|webp)$/i;
// Lower number = preferred when an id has more than one override file.
const EXT_RANK = { svg: 0, webp: 1, png: 2, ico: 3 };

// Target families generated by a `.map`/template in targets.ts expose no literal
// `id:` string for the parser below, so list the icon ids they resolve to here.
// Needed for a templated family whose shared icon has NO literal target to anchor
// it (tg-dc* → tg-dcN, linode-* → linode, vultr-* → vultr). Families that alias to an
// icon owned by a literal target (cf-* → cloudflare, aws-* → cloudfront) are kept.
const DYNAMIC_ICON_IDS = ["tg-dc1", "tg-dc2", "tg-dc3", "tg-dc4", "tg-dc5", "linode", "vultr", "huaweicloud"];

/**
 * The set of icon FILES (e.g. "cloudflare.png", "akamai.svg") that some live
 * target resolves to — mirrors the resolution in targets.ts:
 *   iconId = aws-* → cloudfront | ICON_ALIAS[id] ?? id
 *   file   = <override filename for iconId> ?? `${iconId}.png`
 */
async function usedIconFiles(overrideFor) {
  // Target ids live in the per-group files under config/targets/; ICON_ALIAS still
  // lives in config/targets.ts (the finalization layer). Read both.
  const mainSrc = await readFile(TARGETS, "utf8");
  let combined = mainSrc;
  try {
    for (const f of (await readdir(TARGETS_DIR)).sort()) {
      if (f.endsWith(".ts")) combined += "\n" + (await readFile(path.join(TARGETS_DIR, f), "utf8"));
    }
  } catch {
    /* no targets folder */
  }

  // Literal `id: "..."` values. The `$` exclusion skips template-literal ids
  // (e.g. `tg-dc${dc}`, `aws-${region}`) — those are covered by DYNAMIC_ICON_IDS
  // / ICON_ALIAS instead.
  const ids = new Set(DYNAMIC_ICON_IDS);
  for (const m of combined.matchAll(/\bid:\s*[`"']([^`"'$]+)[`"']/g)) ids.add(m[1]);

  // ICON_ALIAS object literal (in targets.ts): `"id": "iconId",`.
  const alias = {};
  const aliasBlock = mainSrc.match(/const ICON_ALIAS[^=]*=\s*{([\s\S]*?)};/);
  if (aliasBlock) {
    for (const m of aliasBlock[1].matchAll(/[`"']([^`"']+)[`"']\s*:\s*[`"']([^`"']+)[`"']/g))
      alias[m[1]] = m[2];
  }

  const files = new Set();
  for (const id of ids) {
    const iconId = id.startsWith("aws-") ? "cloudfront" : alias[id] ?? id;
    files.add(overrideFor.get(iconId) ?? `${iconId}.png`);
  }
  return files;
}

async function main() {
  await mkdir(OUT, { recursive: true });
  let entries = [];
  try {
    entries = await readdir(SRC);
  } catch {
    return; // no override folder
  }

  // Pick one file per id (svg wins over png, etc.).
  const chosen = new Map(); // id -> { name, ext }
  for (const name of entries) {
    if (!ICON_RE.test(name)) continue;
    const ext = name.slice(name.lastIndexOf(".") + 1).toLowerCase();
    const id = name.slice(0, name.lastIndexOf("."));
    const prev = chosen.get(id);
    if (!prev || EXT_RANK[ext] < EXT_RANK[prev.ext]) chosen.set(id, { name, ext });
  }

  // Non-png override filename per id (what targets.ts serves instead of <id>.png).
  const overrideFor = new Map(); // iconId -> filename
  for (const [id, { name, ext }] of chosen) {
    if (ext !== "png") overrideFor.set(id, name);
  }

  const keep = await usedIconFiles(overrideFor);

  let copied = 0;
  const nonPng = []; // [id, filename] for the manifest (used overrides only)
  for (const [id, { name, ext }] of [...chosen].sort()) {
    const file = ext === "png" ? `${id}.png` : name;
    if (!keep.has(file)) continue; // staged override for a non-target — skip
    // Drop any stale same-id files of other extensions so each id maps to one
    // asset (e.g. remove a leftover auto-fetched `<id>.png` next to a new svg).
    for (const e of Object.keys(EXT_RANK)) {
      if (e !== ext) await rm(path.join(OUT, `${id}.${e}`), { force: true });
    }
    await copyFile(path.join(SRC, name), path.join(OUT, name));
    copied++;
    console.log(`↑ override ${name}`);
    if (ext !== "png") nonPng.push([id, name]);
  }
  if (copied) console.log(`Applied ${copied} icon override(s).`);

  // Prune public/icons/: delete any icon file no live target resolves to.
  let pruned = 0;
  for (const name of await readdir(OUT)) {
    if (!ICON_RE.test(name) || keep.has(name)) continue;
    await rm(path.join(OUT, name), { force: true });
    pruned++;
    console.log(`✗ prune ${name}`);
  }
  if (pruned) console.log(`Pruned ${pruned} unused icon(s).`);

  const body = nonPng.map(([id, name]) => `  ${JSON.stringify(id)}: ${JSON.stringify(name)},`).join("\n");
  const ts =
    `// AUTO-GENERATED by scripts/sync-icons.mjs — do not edit by hand.\n` +
    `// Maps a target id to its icon filename when it is NOT the default\n` +
    `// \`<id>.png\` (i.e. an svg/webp/ico override). Lets the app serve vector\n` +
    `// icons directly. Regenerated on every \`pnpm dev\`/\`build\`.\n` +
    `export const ICON_OVERRIDES: Record<string, string> = {\n${body}${body ? "\n" : ""}};\n`;
  await writeFile(MANIFEST, ts);
  console.log(`Wrote ${nonPng.length} non-png entr${nonPng.length === 1 ? "y" : "ies"} to src/config/icon-overrides.ts`);
}

main();