// Copies manual icon overrides from icons-override/ into public/icons/,
// overwriting the auto-fetched versions. Runs automatically before dev/build
// (predev/prebuild), so overrides always win. Offline and fast.
//
// It also emits src/config/icon-overrides.ts, a generated map of target id ->
// icon filename for every override that is NOT the default `<id>.png` (i.e. an
// svg/webp/ico). targets.ts reads it so the app can serve vector (svg) icons
// directly — no rasterization needed. Drop an `<id>.svg` in icons-override/ and
// it just works on the next dev/build.
import { mkdir, readdir, copyFile, writeFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "icons-override");
const OUT = path.join(ROOT, "public", "icons");
const MANIFEST = path.join(ROOT, "src", "config", "icon-overrides.ts");

const ICON_RE = /\.(png|svg|ico|webp)$/i;
// Lower number = preferred when an id has more than one override file.
const EXT_RANK = { svg: 0, webp: 1, png: 2, ico: 3 };

async function main() {
  await mkdir(OUT, { recursive: true });
  let entries = [];
  try {
    entries = await readdir(SRC);
  } catch {
    return; // no override folder
  }

  // Pick one file per id (svg wins over png, etc.).
  const chosen = new Map(); // id -> filename
  for (const name of entries) {
    if (!ICON_RE.test(name)) continue;
    const ext = name.slice(name.lastIndexOf(".") + 1).toLowerCase();
    const id = name.slice(0, name.lastIndexOf("."));
    const prev = chosen.get(id);
    if (!prev || EXT_RANK[ext] < EXT_RANK[prev.ext]) chosen.set(id, { name, ext });
  }

  let copied = 0;
  const nonPng = []; // [id, filename] for the manifest
  for (const [id, { name, ext }] of [...chosen].sort()) {
    // Drop any stale same-id files of other extensions so each id maps to one
    // asset (e.g. remove a leftover auto-fetched `<id>.png` next to a new svg).
    for (const e of Object.keys(EXT_RANK)) {
      if (e !== ext) await rm(path.join(OUT, `${id}.${e}`), { force: true });
    }
    await copyFile(path.join(SRC, name), path.join(OUT, name));
    copied++;
    console.log(`↑ override ${name}`);
    if (ext !== "png") nonPng.push([id, name]);
  }
  if (copied) console.log(`Applied ${copied} icon override(s).`);

  const body = nonPng.map(([id, name]) => `  ${JSON.stringify(id)}: ${JSON.stringify(name)},`).join("\n");
  const ts =
    `// AUTO-GENERATED by scripts/sync-icons.mjs — do not edit by hand.\n` +
    `// Maps a target id to its icon filename when it is NOT the default\n` +
    `// \`<id>.png\` (i.e. an svg/webp/ico override). Lets the app serve vector\n` +
    `// icons directly. Regenerated on every \`pnpm dev\`/\`build\`.\n` +
    `export const ICON_OVERRIDES: Record<string, string> = {\n${body}${body ? "\n" : ""}};\n`;
  await writeFile(MANIFEST, ts);
  console.log(`Wrote ${nonPng.length} non-png entr${nonPng.length === 1 ? "y" : "ies"} to src/config/icon-overrides.ts`);
}

main();